### ISSUE TITLE
[Gallery][WASM] [Textbox] Unintended Text Selection

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/Uno.Themes#1459] opened 2024-08-21 16:13 UTC
## Current behavior
When switching from one component to another via the side menu and then returning to a textbox, the text within the textbox is occasionally pre-selected.

https://github.com/user-attachments/assets/f3ffa846-f580-45dc-9322-d63173b1c8bc

![Screenshot 2024-08-21 at 11 55 29 AM](https://github.com/user-attachments/assets/8d68d440-50be-464c-8745-a445b4d85637)

## Expected behavior
When returning to the textbox after navigating between components, the text should remain unselected

## How to reproduce it (as minimally and precisely as possible)

1. Open **Gallery Canary WSM**.
2. From the side menu, expand **UI Components** and click on **Textbox**.
3. Observe that no text is automatically selected in the textbox.
4. Now, switch to a different component from the side menu, then return to the **Textbox** component.
5. Notice that upon returning, the text in the textbox appears to be automatically selected.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] UWP
- [ ] MacOS

## Anything else we need to know?
Could be related to : https://github.com/unoplatform/uno/pull/17633 , https://github.com/unoplatform/uno/issues/17914

**Comment by MartinZikmund** [comment] 2024-08-26 10:25
@Youssef1313 @ramezgerges does this look familiar?

**Comment by ramezgerges** [comment] 2024-08-26 21:45
This is actually a duplicate of https://github.com/unoplatform/uno/issues/13440. The repro is not component switching, but double clicking. I suspect @jhanvi03 mistakenly double clicked on the "TextBox" item while switching between components.

**Comment by kazo0** [comment] 2024-09-03 17:22
@jhanvi03 can you double check this and maybe sync with @ramezgerges / @MartinZikmund to see if this is perhaps related to the double-click issue?

**Comment by jhanvi03** [comment] 2024-09-09 16:24
Tested using mouse pad and mouse, occasionally I am able to reproduce with single click. Also, with double click on component, the entire section is getting selected.

**Comment by jhanvi03** [comment] 2024-10-17 15:35
Using the latest Canary version, I encountered the same issue when I navigated to Menu -> Community Toolkit -> DataGrid. Upon a single click, the data was selected unexpectedly.

**Versions:**
Package	Referenced version	Updated version
Uno.CommunityToolkit.WinUI.UI.Controls	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/7.1.203)
Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid	[7.1.200](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.200)	[7.1.203](https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid/7.1.203)
Uno.Core.Extensions.Compatibility	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Compatibility/4.1.1)
Uno.Core.Extensions.Disposables	[4.0.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.0.1)	[4.1.1](https://www.nuget.org/packages/Uno.Core.Extensions.Disposables/4.1.1)
Uno.Sdk	[5.3.96](https://www.nuget.org/packages/Uno.Sdk/5.3.96)	[5.6.0-dev.16](https://www.nuget.org/packages/Uno.Sdk/5.6.0-dev.16)


<img width="713" alt="Screenshot 2024-10-17 at 9 27 18 AM" src="https://github.com/user-attachments/assets/05caf572-86ee-4350-8d22-07eb2ce934a1">

**Comment by Kunal22shah** [comment] 2024-11-25 15:24
Its not related to Component switching, but re clicking on the Textbox component and slightly moving the mouse (click and drag) causes the default text to get selected.
![textbox- canaries](https://github.com/user-attachments/assets/080effa5-91fe-419a-89cc-4d5508542cfd)

It seems to be introduced between [5.4.0-dev.198](https://www.nuget.org/packages/Uno.Sdk/5.4.0-dev.198) and [5.4.0-dev.196](https://www.nuget.org/packages/Uno.Sdk/5.4.0-dev.196)

**Comment by dr1rrb** [comment] 2024-11-26 21:33
IMO this should be fixed by https://github.com/unoplatform/uno/pull/18921 @Xiaoy312 did you validated it?

**Comment by Kunal22shah** [comment] 2024-12-02 18:30
> IMO this should be fixed by [unoplatform/uno#18921](https://github.com/unoplatform/uno/pull/18921) @Xiaoy312 did you validated it?

@dr1rrb I tested on master w the latest changes from Xiao, unable to repro this now. (https://github.com/unoplatform/uno/pull/18931)
![pointer fixed ](https://github.com/user-attachments/assets/4fb600b7-9694-40c0-8341-38587ae3bea8)

**Comment by Xiaoy312** [comment] 2024-12-03 14:33
@Kunal22shah 
unable to repro at all (before and after), or
no longer repro with the fix?

**Comment by Kunal22shah** [comment] 2024-12-03 14:55
@Xiaoy312 no longer able to repro with your fix.

**Closed** 2024-12-03 17:03 UTC
Labels: kind/bug, area/canary
