### ISSUE TITLE
Winui app with CommandBar and Material resources crashes on Windows

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/Uno.Themes#913] opened 2023-01-25 20:47 UTC
### Current behavior

USing `CommandBar `control with MaterialResources crashes app with `UnhandledException`:
"Error HRESULT E_FAIL has been returned from a call to a COM component."
It works when I remove `MaterialResources` line from `App.xaml`.

[TestApp1.zip](https://github.com/unoplatform/uno/files/10503498/TestApp1.zip)

### Expected behavior

It shouldn't crash

### Workaround

If I put Material stuff inside `XamlControlsResources.MergedDictionaries`, as documented in the Readme file for CommunityToolkit, it seems to work (for example, Material style is applied to a `Button`) :

      <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" >
                    <XamlControlsResources.MergedDictionaries>

                        
                        
                        <MaterialColors xmlns="using:Uno.Material" />
                        <MaterialFonts xmlns="using:Uno.Material" />
                        <MaterialResources xmlns="using:Uno.Material" />
   
                    </XamlControlsResources.MergedDictionaries>
                </XamlControlsResources>

But it crashes again if I set a style on CommandBar
`
     <muxc:CommandBar x:Name="mainCommandBar"
                         HorizontalAlignment="Stretch"
                         Style="{StaticResource MaterialCommandBarStyle}"
                         >
`

See comments in `App.xaml` and `MainPage.xaml`

### Works on UWP/WinUI

No

### NuGet package version(s)

		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.3" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.196" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
		<PackageReference Include="Uno.Material.WinUI" Version="2.4.1" />
		<PackageReference Include="Uno.Toolkit.WinUI.Material" Version="2.4.2" />

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.4.4

**Comment by kazo0** [comment] 2023-01-25 21:43
Thanks for the report @ttustonic!

I will take a look, sounds like the MaterialCommandBarStyle is referencing a non-existent resource somewhere

**Comment by kazo0** [comment] 2023-01-25 21:50
Actually, looks like there was already [an issue logged](https://github.com/unoplatform/Uno.Themes/issues/914) for this but it was submitted to the Toolkit repo instead of Themes. I have transferred that issue to the Themes repo and I'll close this one as a duplicate.

You can track the issue with https://github.com/unoplatform/Uno.Themes/issues/914

**Comment by kazo0** [comment] 2023-01-25 21:51
Duplicate of #914

**Closed by kazo0** 2023-01-25 21:51 UTC
Labels: kind/bug, theme/material

**Comment by kazo0** [comment] 2023-01-25 22:03
@ttustonic I'm curious where you found that guidance to place the `MaterialFonts`/`MaterialColors`/`MaterialResources` inside of the `MergedDictionaries` of `XamlControlsResources`.

In our [documentation here](https://platform.uno/docs/articles/external/uno.themes/doc/material-getting-started.html), its specified that you should be placing the Material items within the main Application's `ResourceDictionary.MergedDictionaries`, like so:

```xml
 <Application ...>
 	<Application.Resources>
 		<ResourceDictionary>
 			<ResourceDictionary.MergedDictionaries>

 				<!-- Load WinUI resources -->
 				<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />

 				<!-- Load Uno.Material resources -->
 				<MaterialColors xmlns="using:Uno.Material" />
 				<MaterialFonts xmlns="using:Uno.Material" />
 				<MaterialResources xmlns="using:Uno.Material" />

 				<!-- Load custom application resources -->
 				<!-- ... -->

 			</ResourceDictionary.MergedDictionaries>
 		</ResourceDictionary>
 	</Application.Resources>
 </Application>
```

Is there some documentation somewhere that mentions placing it inside the `XamlControlsResources.MergedDictionaries`?

**Comment by ttustonic** [comment] 2023-01-25 22:12
It was in a ReadMe.txt which opened in VS when I installed CommunityYoolkit.WinUI.Ui.Controls.
It should be in the nuget packages folder:
D:\nuget\packages\communitytoolkit.winui.ui.controls\7.1.2
It should be somewhere in the repo, but I'm too lazy too look for it :)

[ReadMe.txt](https://github.com/unoplatform/Uno.Themes/files/10504125/ReadMe.txt)

**Comment by kazo0** [comment] 2023-01-26 18:11
Interesting, thanks for pointing this out!

**Comment by ttustonic** [comment] 2023-01-26 18:39
Thanks, I already used it before.
However, it seems that I cannot use Font or Symbol icons in NavigationBar (and I'm quite sure that it worked before in Uwp/Net6 project).

**Comment by kazo0** [comment] 2023-01-26 19:25
Yes unfortunately only BitmapIcons are working for the NavigationBar, this is a limitation on iOS and Android only. For other platforms all IconElements should be supported.

I will track down the issue we have logged for that, hopefully we can find a way but it really depends on what we are able to accomplish with the native Toolbar (Android) and UINavigationBar (iOS)

**Comment by ttustonic** [comment] 2023-01-26 22:27
Ah, well, at least I don't have to try anymore.
Thanks, Tom
