### ISSUE TITLE
[WASM][Material] Date picker hard shadows

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/Uno.Themes#972] opened 2023-04-07 14:17 UTC
## Current behavior
<img width="290" alt="image" src="https://user-images.githubusercontent.com/78549750/230623446-6085adcd-93a3-4d1c-869e-1a77fc1257d8.png">

## Expected behavior

The shadows should display more softly. 
## How to reproduce it (as minimally and precisely as possible)
1. Launch https://gallery.platform.uno 
2. Open DatePicker with Material

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] [Android](https://github.com/unoplatform/Uno.Gallery/issues/1035)
- [x] WebAssembly
- [ ] UWP
- [ ] MacOS

**Comment by weitzhandler** [comment] 2023-10-29 00:57
Seems like a duplicate of https://github.com/unoplatform/Uno.Gallery/issues/1035

**Closed** 2023-11-03 11:56 UTC
Labels: kind/bug
