### ISSUE TITLE
[iOS] Text alignment issues when using custom Material Font

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Themes#837] opened 2022-08-25 15:39 UTC
<img width="248" alt="image" src="https://user-images.githubusercontent.com/4793020/186709136-130dca33-e936-4333-bfbf-2e6be8317e92.png">

## Expected behavior

Should match Android

## How to reproduce it (as minimally and precisely as possible)

repro attached

[TextBlockiOSBug.zip](https://github.com/unoplatform/Uno.Themes/files/9426182/TextBlockiOSBug.zip)

**Comment by Xiaoy312** [comment] 2022-08-25 15:41
xref: https://dev.azure.com/nventive/Isaac/_workitems/edit/261770

**Comment by Xiaoy312** [comment] 2022-08-26 20:06
duplicate of #832, and i can confirm it is fixed with #834

![image](https://user-images.githubusercontent.com/2359550/186983053-bd852807-20ff-40c4-97ab-2200d41e37ac.png)
![image](https://user-images.githubusercontent.com/2359550/186983061-44b572f6-e024-41c9-bd9e-4a5efd23c923.png)

**Closed by Xiaoy312** 2022-08-26 20:06 UTC
Labels: kind/bug, theme/material, platform/ios
