### ISSUE TITLE
Material could not be found

### ISSUE THREAD

**Issue by mediatech15** [unoplatform/Uno.Themes#427] opened 2020-10-09 16:24 UTC
## Current behavior

Installation of the package and following readme.

## Expected behavior

References resolve. or readme updated for proper usage.

## How to reproduce it (as minimally and precisely as possible)

Create a new Uno project in VS 2019 (based on templates from extension)
Setup project for build of UWP (disabled by default)
Install Uno.Material
Follow to the letter the Readme.md for steps 1-4 
Receive Errors 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Material' could not be found (are you missing a using directive or an assembly reference?)	App2.Droid, App2.UWP, App2.Wasm, App2.iOS, App2.macOS	C:\Users\Kylee\source\repos\App2\App2\App2.Shared\App.xaml.cs	47	Active

## Environment

Nuget Package: Yes

Package Version(s): 1.0.0-dev.515

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] UWP
- [ ] MacOS

## Anything else we need to know?

 
Running VS 2019 16.7.5

**Comment by jeromelaban** [comment] 2020-10-09 16:48
Thanks for the report. Can you validate that your project's name does not ends by ".Uno"? If it does, it's the cause of this issue and will be fixed by Uno 3.1.

**Comment by mediatech15** [comment] 2020-10-09 16:49
My solution is 'App2' and the sub projects are
'App2.Droid', 'App2.iOS', 'App2.macOS', 'App2.Shared', 'App2.UWP', 'App2.Wasm'

**Comment by mediatech15** [comment] 2020-10-09 16:54
Also I have tried the 3.1 Uno.UI builds from other issues for other things I found. This issue is the same on both DEV and STABLE.

**Comment by jeromelaban** [comment] 2020-10-09 20:35
My apologies, I did not notice the app name. Then it could be something else.

Could you attach your solution you built to this issue ? We may have missed something else.

**Comment by mediatech15** [comment] 2020-10-09 20:38
[App2.zip](https://github.com/unoplatform/Uno.Material/files/5357396/App2.zip)

**Comment by jeromelaban** [comment] 2020-10-09 20:57
Thanks. You'll need to add `Uno.` in front of material to fix this issue, and change `ms-appx:///Views/ColorPaletteOverride.xaml` to `ms-appx:///ColorPaletteOverride.xaml`, as the path of the file in your application is at the root.

We'll adjust the documentation.

**Comment by mediatech15** [comment] 2020-10-09 21:03
That's interesting cause intellisense suggested that and when I tried it there was the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'ResourceDictionary' is defined in an assembly that is not referenced. You must add a reference to assembly 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'.	App3.UWP	C:\Users\Kylee\source\repos\App3\App3\App3.Shared\App.xaml.cs	46	Active

Note that this is a different test project that I used to try to get around this problem

**Comment by mediatech15** [comment] 2020-10-09 21:04
```
protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            // Set a default palette to make sure all colors used by MaterialResources exist
            this.Resources.MergedDictionaries.Add(new Uno.Material.MaterialColorPalette());

            // Overlap the default colors with the application's colors palette. 
            // TODO: Replace ms-appx:///Views/ColorPaletteOverride.xaml with your resourceDictionary.
            this.Resources.MergedDictionaries.Add(new ResourceDictionary() { Source = new Uri("ms-appx:///ColorPaletteOverride.xaml") });

            // Add all the material resources. Those resources depend on the colors above, which is why this one must be added last.
            this.Resources.MergedDictionaries.Add(new Uno.Material.MaterialResources());
```

**Comment by mediatech15** [comment] 2020-10-09 21:06
In the App2 project this resolves it. But my testing had that but didn't have success.

**Comment by mediatech15** [comment] 2020-10-20 15:14
This i found has to do with the target SDK for UWP app. The default uno projects are 1809 but Material requires 1903

**Closed** 2021-02-11 23:19 UTC
